### ISSUE TITLE
pickle file not available 

### ISSUE THREAD

**Issue by Joshjj1** [kikiru328/KiTs21#1]
could you please share the pickle file used in the below code :  

for i in tqdm(range(1),desc = 'Train_images'):
    with open('/root/project/code/kits/Trials/multisegmentation/pkls/train_images.pkl','rb') as images:
        train_images = pickle.load(images)
for i in tqdm(range(1),desc = 'Train_masks'):   
    with open('/root/project/code/kits/Trials/multisegmentation/pkls/train_masks.pkl','rb') as masks:
        train_masks = pickle.load(masks) .

**Comment by kikiru328** [comment]
I'm sorry, but it's been a long time since I've worked on this project, so I don't think I can find the PICKLE file.

**Comment by Joshjj1** [comment]
ok, no worries.
